### ISSUE TITLE
slackin 메일 발송 안됨...

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/codeforseoul.github.io#21]
저번에 서버 초기화 후 os 업그레이드한 후 메일 발송 설정도 함께 다른 우주로~

**Comment by thechunsik** [comment]
명왕성따라 갔나보ㅏ요

**Comment by mozodev** [comment]
아 착각이었네요... 우리 서버가 보내는게 아니라 slack.com이 메일을 보내는 거고 테스트해봤는데 잘 오네요. 근데 요새 좀 뜸한거 같아서 메일이 안가나보다 했어요... 닫습니다.
