### ISSUE TITLE
codeforseoul.org 2.0 개편

### ISSUE THREAD

**Issue by hoony** [codeforseoul/codeforseoul.github.io#23]
홈페이지 개편에 대한 의견을 모아주세요. 코드 뿐만 아니라 자유로운 의견도 큰 기여가 됩니다!

## 개편에 들어갈 컨텐츠

1. 새롭게 참여하기
  - Code of Conduct
  - 참여 방법(슬랙, 깃헙 등등)
2. 코드포서울 보여주기
  - 코드포-란? 코드포서울 커뮤니티란?
  - 활동가 / 프로젝트 / 밋업 목록(자동화?)
3. 코드포- 보여주기
  - 코드포- 현황(국제, 국내 둘다?)
4. 오픈 뱃지

**Comment by mozodev** [comment]
저번 주 송년회 마치고 이래저래 생각하다가 일단 미국이랑 올 돌아다니다가 좋은 리소스들이 있어서 정리하고 있습니다. 

코드포서울 짐 나눠갖기 
https://docs.google.com/document/d/1GcSgjFXj_IHtlsVU22L4PAz39afrVy_DfMe0zwlMIE4/edit

일단 가장 중요한 건 what you can do
https://www.codeforamerica.org/join

홍보 동영상 만들기 위해 이야기하다가 정리해본 문서입니다.
https://docs.google.com/document/d/1u0GORxlGtDrZPX5zXb__6UKgepdnEP3A24BpB9zvijE/edit

뭔가 해보고 싶은데 뭘 할 수 있을까? 이런 질문 뭔가 반응해야하지 않을까? 하는 생각이 들어요.

**Comment by hoony** [comment]
이 이슈는 닫을게요, 위에 댓글 다신 내용들은 각 개별 이슈로 따로 열어주시면 감사하겠습니다! @mozodev
